### ISSUE TITLE
Task Exception

### ISSUE THREAD

**Issue by Rhbarber** [ZombieStriker/QualityArmoryVehicles2#178]
[08:05:56 WARN]: [QualityArmoryVehicles2] Task #87 for QualityArmoryVehicles2 v2.3.4 generated an exception
java.lang.NullPointerException: null
        at me.zombie_striker.qav.util.BlockCollisionUtil.getHeight(BlockCollisionUtil.java:45) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.util.BlockCollisionUtil.isSolidAt(BlockCollisionUtil.java:58) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.vehicles.AbstractVehicle.basicDirections(AbstractVehicle.java:447) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.vehicles.AbstractVehicle.basicDirections(AbstractVehicle.java:334) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.vehicles.AbstractCar.tick(AbstractCar.java:102) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.VehicleEntity.tick(VehicleEntity.java:221) ~[QualityArmoryVehicles.jar:?]
        at me.zombie_striker.qav.Main$1.run(Main.java:230) ~[QualityArmoryVehicles.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1875]
        at net.minecraft.server.MinecraftServer$$Lambda$4377/0x0000000002a49950.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

Server Version: git-Purpur-1875 (MC: 1.19.3)
Plugin Version: QualityArmoryVehicles2 version 2.3.4
QA Version: QualityArmory version 2.0.8.1
Plugins (31): Citizens, CoreProtect, DeltaPunishments, Elevators, Essentials, EssentialsChat, EssentialsMysqlStorage, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, HolographicDisplays, LightAPI, LiteBans, LuckPerms, NBTAPI, NoChatReports, OldCombatMechanics, Panilla, PlaceholderAPI, Plan, PlotSquared, ProtocolLib, QualityArmory, QualityArmoryVehicles2, SafeNET, SkinsRestorer, TAB, TigerReports, Vault, Vulcan, WorldGuard

**Comment by Lorenzo0111** [comment]
Fixed.
